app-name = "hasura_auth"
version = 1.0
# 服务端口
address = ":3016"

[auth]
# jwt sign secret
jwt-secret = "123456"
# jwt expired time in second
jwt-expire-in = "86400s"

# 下游 graphql 服务 host
[hasura]
host = "http://127.0.0.1:3000"
